name: MacClipboard

options:
  minimumXcodeGenVersion: 2.38.0

settings:
  base:
    SWIFT_VERSION: 5.9
    MACOSX_DEPLOYMENT_TARGET: 12.0

targets:
  MacClipboard:
    type: application
    platform: macOS
    deploymentTarget: "12.0"
    sources:
      - path: App
      - path: Models
      - path: ViewModels
      - path: Views
      - path: Services
      - path: Utilities
      - path: App/AppIcon.icns
        type: file
    settings:
      PRODUCT_NAME: MaClip
      PRODUCT_BUNDLE_IDENTIFIER: com.jokot.MacClipboard
      INFOPLIST_FILE: App/Info.plist
      CURRENT_PROJECT_VERSION: 5
      MARKETING_VERSION: 1.4.0
      DEFINES_MODULE: YES
    scheme:
      testTargets:
        - MacClipboardTests

  MacClipboardTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "12.0"
    sources:
      - path: Tests/MacClipboardTests
    dependencies:
      - target: MacClipboard
    settings:
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/MaClip.app/Contents/MacOS/MaClip"
      BUNDLE_LOADER: "$(TEST_HOST)"
      GENERATE_INFOPLIST_FILE: YES

