import Foundation
import Cocoa
import Combine

protocol ClipboardMonitorProtocol {
    var itemPublisher: AnyPublisher<ClipboardItem, Never> { get }
    func start()
    func stop()
    func ignoreCurrentChangeCount()
}

final class ClipboardMonitor: ClipboardMonitorProtocol {
    private let subject = PassthroughSubject<ClipboardItem, Never>()
    var itemPublisher: AnyPublisher<ClipboardItem, Never> { subject.eraseToAnyPublisher() }

    private var timer: Timer?
    private var lastChangeCount: Int = NSPasteboard.general.changeCount

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.75, repeats: true) { [weak self] _ in
            self?.pollPasteboard()
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func ignoreCurrentChangeCount() {
        lastChangeCount = NSPasteboard.general.changeCount
    }

    private func pollPasteboard() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount
        NSLog("[MaClip] pollPasteboard: types=\(pb.types?.map(\.rawValue) ?? [])")

        let frontmost = NSWorkspace.shared.frontmostApplication
        let sourceBundleID = frontmost?.bundleIdentifier

        // Self-capture guard. Belt-and-suspenders against any race in
        // ClipboardListViewModel.setPasteboard's ignoreCurrentChangeCount() (1.6.0).
        if sourceBundleID == "com.jokot.MacClipboard" { return }

        // Exclusion list — never ingest from these apps.
        if let id = sourceBundleID,
           AppSettings.shared.excludedBundleIDs.contains(id) {
            return
        }

        // Concealed UTI detection. Inspect types BEFORE reading data.
        let concealedUTIs: Set<String> = [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.AutoGeneratedType",
            "com.apple.is-sensitive",
        ]
        let isConcealed: Bool = {
            guard let types = pb.types else { return false }
            return types.contains { concealedUTIs.contains($0.rawValue) }
        }()

        if isConcealed && AppSettings.shared.skipConcealedItems {
            return
        }

        let expiry: Date? = isConcealed
            ? Date().addingTimeInterval(AppSettings.shared.concealedClearTimeout)
            : nil

        // Read content (image > URL > text) — same priority as before.
        if let image = readImage(from: pb) {
            let imgContent = ImageContent(source: .memory(image),
                                          cachedText: nil, cachedId: nil, cachedBarcode: nil)
            subject.send(ClipboardItem(
                date: Date(), content: .image(imgContent),
                sourceBundleID: sourceBundleID,
                isConcealed: isConcealed,
                concealedExpiresAt: expiry
            ))
            return
        }

        if let url = readURL(from: pb) {
            subject.send(ClipboardItem(
                date: Date(), content: .url(url),
                sourceBundleID: sourceBundleID,
                isConcealed: isConcealed,
                concealedExpiresAt: expiry
            ))
            return
        }

        if let text = readText(from: pb) {
            let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
            if let detected = URLUtils.linkURL(from: trimmed) {
                subject.send(ClipboardItem(
                    date: Date(), content: .url(detected),
                    sourceBundleID: sourceBundleID,
                    isConcealed: isConcealed,
                    concealedExpiresAt: expiry
                ))
            } else {
                subject.send(ClipboardItem(
                    date: Date(), content: .text(text),
                    sourceBundleID: sourceBundleID,
                    isConcealed: isConcealed,
                    concealedExpiresAt: expiry
                ))
            }
        }
    }

    private func readText(from pasteboard: NSPasteboard) -> String? {
        if let items = pasteboard.pasteboardItems, !items.isEmpty {
            let item = items[0]
            if let str = item.string(forType: .string) { return str }
        }
        return nil
    }

    private func readURL(from pasteboard: NSPasteboard) -> URL? {
        if let objs = pasteboard.readObjects(forClasses: [NSURL.self], options: nil) as? [URL], let url = objs.first {
            return url
        }
        if let items = pasteboard.pasteboardItems, let item = items.first {
            if let s = item.string(forType: .URL), let url = URL(string: s) { return url }
            // Some apps use public.url
            if let s = item.string(forType: NSPasteboard.PasteboardType("public.url")), let url = URL(string: s) { return url }
        }
        return nil
    }

    private func readImage(from pasteboard: NSPasteboard) -> NSImage? {
        // Try robust Cocoa reading first
        if let objs = pasteboard.readObjects(forClasses: [NSImage.self], options: nil) as? [NSImage],
           let img = objs.first {
            return img
        }
        // Fallback: inspect first pasteboard item data for common image types
        if let items = pasteboard.pasteboardItems, let item = items.first {
            if let data = item.data(forType: .tiff), let image = NSImage(data: data) {
                return image
            }
            if let data = item.data(forType: .png), let image = NSImage(data: data) {
                return image
            }
        }
        return nil
    }
}